"""
Client onboarding -- one command from a bare ``Name`` + ``domain`` to a fully wired
audit target.

Today, onboarding a new client means hand-authoring three things:

  1. ``config/domains/{domain}.framework.yaml`` -- the ideal-site taxonomy
     (already automatable via :func:`aeo.reference.framework_bootstrap.bootstrap_framework`,
     just not wired into a single onboarding step).
  2. ``config/domains/{domain}.yaml`` -- the per-run onboarding override
     (domain/topic/engine_target/label -- see ``securin.io.yaml``).
  3. ``config/entities.yaml`` -- the entity dictionary (canonical name, aliases,
     first-person markers, domain) for the client AND its competitors, used by
     ``extract.entities`` for first-person/citation scoring.

:func:`onboard_client` chains all three plus competitor discovery
(:mod:`aeo.reference.competitor_discovery`) and target registration
(``storage.repos.targets``), so the operator runs one command, reviews the
generated files, and is ready for ``aeo audit-cycle``.

Every sub-step is independently safe to fail: a down LLM degrades to the generic
framework skeleton and zero discovered competitors rather than aborting onboarding
-- the operator still gets a registered target and can fill in the rest by hand.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

import yaml

from ..logging import get_logger
from ..nlp.llm import LLMClient
from ..settings import get_settings
from ..storage.models import Target
from ..storage.repos import targets as targets_repo
from .competitor_discovery import (
    CompetitorDiscoveryResult,
    DiscoveredCompetitor,
    discover_competitors,
)
from .domain_config import normalize_domain
from .framework_bootstrap import bootstrap_framework, framework_file_path, write_framework

log = get_logger(__name__)

_DEFAULT_FIRST_PERSON = ["we", "our", "us", "ours", "ourselves"]

# Mirrors `domain_config._VALID_ENGINES` (kept local rather than importing a private
# name across modules -- both must change together if the engine_target contract grows).
_VALID_ENGINE_TARGETS = {"perplexity", "chatgpt_search", "gemini", "generic"}


# -- config/domains/{domain}.yaml -- the per-run onboarding override file -----

def _domain_config_path(domain: str, config_dir: Path | None = None) -> Path:
    base = config_dir or Path(get_settings().config_dir)
    return base / "domains" / f"{normalize_domain(domain)}.yaml"


def _write_domain_config(
    name: str,
    domain: str,
    *,
    topic: str,
    engine_target: str | None,
    max_urls: int | None,
    label: str | None,
    config_dir: Path | None = None,
    overwrite: bool = False,
) -> tuple[Path, bool]:
    """Write ``config/domains/{domain}.yaml`` (the file ``securin.io.yaml`` models).

    Returns ``(path, written)`` -- ``written`` is False when the file already exists
    and ``overwrite`` is False (onboarding must stay re-run-safe without clobbering
    hand-edits)."""
    host = normalize_domain(domain)
    path = _domain_config_path(domain, config_dir)
    if path.exists() and not overwrite:
        return path, False

    path.parent.mkdir(parents=True, exist_ok=True)
    engine = engine_target if engine_target in _VALID_ENGINE_TARGETS else "generic"
    lines = [
        f"# Per-domain onboarding config for {host}.",
        "# Overrides the global reference_architecture settings for this client per run.",
        "# Auto-generated by `aeo onboard` -- review engine_target/topic, then run `aeo audit-cycle`.",
        "",
        f"domain: {host}",
        "",
        "# Topic taxonomy this client is measured against (must exist in framework.yaml,",
        "# or be served by the per-domain framework.yaml generated alongside this file).",
        f"topic: {topic}",
        "",
        "# Answer engine to optimize toward. Routes the blueprint-synthesis prompt emphasis:",
        "#   perplexity     -> citation density",
        "#   chatgpt_search -> conversational coverage",
        "#   gemini         -> structured entity coverage",
        "#   generic        -> engine-neutral",
        f"engine_target: {engine}",
    ]
    if max_urls is not None:
        lines += ["", "# Discovery cap before prioritization (omit to use crawler.discovery.max_urls).", f"max_urls: {max_urls}"]
    if label:
        lines += ["", "# Run label.", f'label: "{label}"']
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path, True


# -- config/entities.yaml -- append-only merge, preserves hand-curated entries -

def _entities_path(config_dir: Path | None = None) -> Path:
    base = config_dir or Path(get_settings().config_dir)
    return base / "entities.yaml"


def _existing_entities(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception as exc:
        log.warning("entities_yaml_unreadable", path=str(path), error=str(exc))
        return {}
    return raw.get("entities", {}) if isinstance(raw, dict) else {}


_KEY_RE = re.compile(r"^[A-Za-z][A-Za-z0-9 _-]*$")


def _yaml_key(name: str) -> str:
    """Quote the entity key only when the bare form would need it (mirrors the
    quoting already present in entities.yaml, e.g. ``"XM Cyber"``, ``Securin``)."""
    return name if _KEY_RE.match(name) else yaml.safe_dump(name).strip().removesuffix("...").strip()


def _entity_block(name: str, *, canonical: str, aliases: list[str], domain: str | None, first_person: list[str]) -> str:
    alias_list = ", ".join(json.dumps(a) for a in aliases) if aliases else ""
    fp_list = ", ".join(json.dumps(p) for p in first_person)
    lines = [
        f"  {_yaml_key(name)}:",
        f"    canonical: {canonical}",
        f"    aliases: [{alias_list}]",
        f"    first_person: [{fp_list}]",
    ]
    if domain:
        lines.append(f"    domain: {domain}")
    return "\n".join(lines)


@dataclass(slots=True)
class EntityMergeResult:
    added: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)  # already present (by canonical name or domain)


def _merge_entities(
    *,
    client_name: str,
    client_domain: str,
    competitors: list[DiscoveredCompetitor],
    config_dir: Path | None = None,
) -> tuple[Path, EntityMergeResult]:
    """Append the client + verified competitors to ``entities.yaml`` as new top-level
    keys under ``entities:``. Text-append rather than full re-dump: a YAML round-trip
    via ``safe_dump`` would nuke the file's header comments and per-entry annotations,
    which are exactly what makes this dictionary reviewable. Idempotent -- anything
    already present (by canonical name OR domain, case-insensitive) is skipped."""
    path = _entities_path(config_dir)
    existing = _existing_entities(path)
    existing_names = {str(k).lower() for k in existing}
    existing_domains = {
        normalize_domain(str(v.get("domain", ""))) for v in existing.values() if isinstance(v, dict) and v.get("domain")
    }

    candidates: list[tuple[str, str | None, list[str]]] = [(client_name, client_domain, [])]
    candidates += [(c.name, c.domain, c.aliases) for c in competitors]

    blocks: list[str] = []
    result = EntityMergeResult()
    for entity_name, entity_domain, aliases in candidates:
        host = normalize_domain(entity_domain) if entity_domain else None
        if entity_name.lower() in existing_names or (host and host in existing_domains):
            result.skipped.append(entity_name)
            continue
        existing_names.add(entity_name.lower())
        if host:
            existing_domains.add(host)
        blocks.append(_entity_block(entity_name, canonical=entity_name, aliases=aliases, domain=host, first_person=_DEFAULT_FIRST_PERSON))
        result.added.append(entity_name)

    if not blocks:
        return path, result

    if not path.exists():
        header = (
            "# Entity dictionary used by extract/entities.py and scoring/entity_consistency.py.\n"
            "# Each entity has a canonical name and a list of variants/first-person markers.\n"
            "# Matching is case-insensitive but variant strings are matched as whole words.\n\n"
            "entities:\n"
        )
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(header, encoding="utf-8")

    today = date.today().isoformat()
    appendix = (
        f"\n  # --- Auto-discovered by `aeo onboard {client_name}` on {today} -- "
        "review aliases/first_person, then remove this note ---\n"
        + "\n".join(blocks)
        + "\n"
    )
    with path.open("a", encoding="utf-8") as fh:
        fh.write(appendix)
    return path, result


# -- orchestration ------------------------------------------------------------

@dataclass(slots=True)
class OnboardResult:
    client: Target
    competitor_targets: list[Target]
    framework_path: Path
    framework_source: str
    domain_config_path: Path
    domain_config_written: bool
    entities_path: Path
    entities: EntityMergeResult
    discovery: CompetitorDiscoveryResult


def onboard_client(
    name: str,
    domain: str,
    *,
    topic: str | None = None,
    category: str | None = None,
    engine_target: str | None = None,
    max_urls: int | None = None,
    label: str | None = None,
    competitor_count: int = 5,
    use_llm: bool = True,
    llm: LLMClient | None = None,
    config_dir: Path | None = None,
    overwrite_domain_config: bool = False,
) -> OnboardResult:
    """One-shot onboarding: framework -> domain config -> competitor discovery ->
    entities merge -> target registration. Idempotent and safe to re-run -- every
    write step skips/no-ops on what already exists rather than clobbering it."""
    host = normalize_domain(domain)
    if not host:
        raise ValueError(f"not a usable domain: {domain!r}")

    if llm is None and use_llm:
        from ..nlp.llm import get_client
        llm = get_client()
    elif not use_llm:
        llm = None

    # 1. Per-domain ideal-site framework (reuses the existing `aeo framework bootstrap` path).
    fw_path = framework_file_path(host, config_dir)
    if fw_path.exists():
        fw_data = yaml.safe_load(fw_path.read_text(encoding="utf-8")) or {}
        fw_source = "existing"
    else:
        fw_data = bootstrap_framework(host, llm=llm, topic=topic, category=category)
        write_framework(host, fw_data, config_dir=config_dir)
        fw_source = str(fw_data.get("_generated_by", "generic-skeleton"))
    resolved_topic = topic or str(fw_data.get("topic") or name)

    # 2. Per-run onboarding override file.
    dc_path, dc_written = _write_domain_config(
        name, host, topic=resolved_topic, engine_target=engine_target, max_urls=max_urls,
        label=label, config_dir=config_dir, overwrite=overwrite_domain_config,
    )

    # 3. Competitor discovery + live verification.
    discovery = discover_competitors(name, host, topic=resolved_topic, count=competitor_count, llm=llm)

    # 4. Merge client + verified competitors into the entity dictionary.
    ent_path, ent_result = _merge_entities(
        client_name=name, client_domain=host, competitors=discovery.verified, config_dir=config_dir,
    )

    # 5. Register targets (idempotent on name -- re-running just refreshes domain/url).
    client_target = targets_repo.upsert(name, host, "client")
    competitor_targets = [targets_repo.upsert(c.name, c.domain, "competitor") for c in discovery.verified]

    log.info(
        "client_onboarded", name=name, domain=host, framework_source=fw_source,
        competitors_proposed=discovery.raw_count, competitors_verified=len(discovery.verified),
        competitors_dropped=len(discovery.dropped), entities_added=len(ent_result.added),
    )
    return OnboardResult(
        client=client_target,
        competitor_targets=competitor_targets,
        framework_path=fw_path,
        framework_source=fw_source,
        domain_config_path=dc_path,
        domain_config_written=dc_written,
        entities_path=ent_path,
        entities=ent_result,
        discovery=discovery,
    )
